apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  annotations:
    jenkins.io/last-build-number-for-master: "2"
  creationTimestamp: null
  labels:
    jenkins.io/chart-release: repos
    jenkins.io/namespace: jx
    jenkins.io/version: "8"
    owner: prohousing-as
    provider: github
    repository: ph-user-service-serverless
  name: prohousing-as-ph-user-service-serverless
spec:
  description: Imported application for prohousing-as/ph-user-service-serverless
  httpCloneURL: https://github.com/prohousing-as/ph-user-service-serverless.git
  org: prohousing-as
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: ph-user-service-serverless
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/prohousing-as/ph-user-service-serverless.git
